# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "ehci_pci" "sr_mod" "xen_blkfront" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];
  boot.kernelParams = ["video=Virtual-1:1280x720@60"];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/07335022-9792-499b-8cd2-60c6781398c2";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-fcdbee89-22f3-4b82-a40b-61cfff812e94".device = "/dev/disk/by-uuid/fcdbee89-22f3-4b82-a40b-61cfff812e94";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/ce71d2e5-b526-4c42-be30-1d64c504303a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enX0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
