#output Virtual-1 {
#    mode 1920x1200@60hz
#}
exec_always swaymsg output Virtual-1 mode 1920x1200@60hz
# SwayFX specific: disable effects for VM performance
exec_always swaymsg shadows disable
exec_always swaymsg layer_effects "*" disable